

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# Install all of the dependencies on the agent 
- powershell: |
    Invoke-WebRequest -Uri "https://github.com/Azure/bicep/releases/latest/download/bicep-win-x64.exe" -OutFile "bicep.exe"
    .\bicep.exe --version
  displayName: 'Install Bicep CLI'

# Make sure that the directory armtemplates exist so we can put the transpiled .json file into it. We then run the transpile command. 
- powershell: |
    New-Item -Path $(Build.ArtifactStagingDirectory)/coreArmTemplates -ItemType Directory -Force
    .\bicep.exe build $(Build.SourcesDirectory)\Alerts.ARM\Core\main.bicep --outdir $(Build.ArtifactStagingDirectory)/coreArmTemplates
  displayName: 'Transpile Core resources to ARM'


# Make sure that the directory armtemplates exist so we can put the transpiled .json file into it. We then run the transpile command. 
- powershell: |
    New-Item -Path $(Build.ArtifactStagingDirectory)/appArmTemplates -ItemType Directory -Force
    .\bicep.exe build $(Build.SourcesDirectory)\Alerts.ARM\main.bicep --outdir $(Build.ArtifactStagingDirectory)/appArmTemplates
  displayName: 'Transpile App Specific resources to ARM'


# Copy the rest of the core paramater files into the directory so all .json files are available. 
- powershell: |
    Get-ChildItem -Path "$(Build.SourcesDirectory)\Alerts.ARM\Core\parameters.*.json" | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination "$(Build.ArtifactStagingDirectory)/coreArmTemplates"
    }
  displayName: 'Copy all core parameter files to staging directory using PowerShell'


# Copy the rest of the app secific paramater files into the directory so all .json files are available. 
- powershell: |
    Get-ChildItem -Path "$(Build.SourcesDirectory)\Alerts.ARM\parameters.*.json" | ForEach-Object {
        Copy-Item -Path $_.FullName -Destination "$(Build.ArtifactStagingDirectory)/appArmTemplates"
    }
  displayName: 'Copy all app specific parameter files to staging directory using PowerShell'


# Do our build
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)/AlertsApi.zip"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
# Publish the API as ZIP (assuming the output of VSBuild is a ZIP)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(build.artifactStagingDirectory)/AlertsApi.zip'
    artifactName: 'api'
    publishLocation: 'Container'


# Publish ARM Templates
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/appArmTemplates' 
    artifactName: 'appArmTemplates'
    publishLocation: 'Container'


# Publish ARM Templates
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/coreArmTemplates' 
    artifactName: 'coreArmTemplates'
    publishLocation: 'Container'

